--------------------------------------------------------
--  File created - Saturday-June-30-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRITAPP_USERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TRITAPP_USERS" 
   (	"USERID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"USERPASSWORD" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TRITAPP_USERS
SET DEFINE OFF;
Insert into SYSTEM.TRITAPP_USERS (USERID,USERNAME,USERPASSWORD) values (1,'username1','userpass');
Insert into SYSTEM.TRITAPP_USERS (USERID,USERNAME,USERPASSWORD) values (2,'username2','userpass2');
Insert into SYSTEM.TRITAPP_USERS (USERID,USERNAME,USERPASSWORD) values (3,'username3','userpass3');
Insert into SYSTEM.TRITAPP_USERS (USERID,USERNAME,USERPASSWORD) values (4,'username4','userpass4');
Insert into SYSTEM.TRITAPP_USERS (USERID,USERNAME,USERPASSWORD) values (5,'username5','userpass5');
Insert into SYSTEM.TRITAPP_USERS (USERID,USERNAME,USERPASSWORD) values (6,'username6','userpass6');
--------------------------------------------------------
--  DDL for Index SYS_C0010213
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C0010213" ON "SYSTEM"."TRITAPP_USERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TRITAPP_USERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TRITAPP_USERS" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."TRITAPP_USERS" MODIFY ("USERPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TRITAPP_USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger USERID_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."USERID_ON_INSERT" 
  BEFORE INSERT ON TritApp_Users
  FOR EACH ROW
BEGIN
  SELECT auto_increment_userid.nextval
    INTO :new.userID
    FROM dual;
END;
/
ALTER TRIGGER "SYSTEM"."USERID_ON_INSERT" ENABLE;
