--------------------------------------------------------
--  File created - Saturday-June-30-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRITAPP_GROUPS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TRITAPP_GROUPS" 
   (	"GROUPID" NUMBER(*,0), 
	"GROUPNAME" VARCHAR2(30 BYTE), 
	"GROUPMEMBERS" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TRITAPP_GROUPS
SET DEFINE OFF;
Insert into SYSTEM.TRITAPP_GROUPS (GROUPID,GROUPNAME,GROUPMEMBERS) values (1,'New Group Name','1, 2, 3');
Insert into SYSTEM.TRITAPP_GROUPS (GROUPID,GROUPNAME,GROUPMEMBERS) values (2,'Username4 Group','4, 1, 2, 3');
Insert into SYSTEM.TRITAPP_GROUPS (GROUPID,GROUPNAME,GROUPMEMBERS) values (3,'Chat App Group','5, 2, 3, 4');
Insert into SYSTEM.TRITAPP_GROUPS (GROUPID,GROUPNAME,GROUPMEMBERS) values (4,'New Group Here','6, 2, 3');
--------------------------------------------------------
--  DDL for Index SYS_C0010245
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C0010245" ON "SYSTEM"."TRITAPP_GROUPS" ("GROUPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TRITAPP_GROUPS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TRITAPP_GROUPS" ADD PRIMARY KEY ("GROUPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."TRITAPP_GROUPS" MODIFY ("GROUPMEMBERS" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger GROUPID_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."GROUPID_ON_INSERT" 
  BEFORE INSERT ON TritApp_Groups
  FOR EACH ROW
BEGIN
  SELECT auto_increment_groupid.nextval
    INTO :new.groupID
    FROM dual;
END;
/
ALTER TRIGGER "SYSTEM"."GROUPID_ON_INSERT" ENABLE;
